# Project 4: Systems of Linear Equation Solving

This week we will go over Gauss-Jordan and the algorithm to solve it.

# Rows function

Firstly, we need to write methods for operation on rows needed for Jordan-Gauss method, which includes adding, swapping, and multiplying.

Please note that I will make a copy of the matrix list and modify parts needed to be changed instead of appending to a totally new list within the function.

In [36]:
import math
import numpy as np

matrix = np.array([[3,2,3,1], [6,-4,1,2], [9,-2,4,3]])


#SWAP ROWS

def swap(matrx, r1, r2):
    temp = matrx.copy()
    temp[[r1, r2]] = temp[[r2, r1]]
    return np.array(temp)

swap(matrix, 1, 2)    


array([[ 3,  2,  3,  1],
       [ 9, -2,  4,  3],
       [ 6, -4,  1,  2]])

In [37]:
#ADD


def addRow(matrx, row, toAdd, multiplier):
    temp = matrx.copy()
    for i in range(len(matrx[row, :])):
        temp[row, i] = temp[row, i] + multiplier*temp[toAdd, i]
    return np.array(temp)

addRows(matrix, 1, 2, 5)


array([[  3,   2,   3,   1],
       [ 51, -14,  21,  17],
       [  9,  -2,   4,   3]])

In [38]:
def toLeading1(matrx, row, col):
    temp = matrx.copy()
    temp = np.array(temp, float)
    temp[row, :] = temp[row, :]/temp[row, col]
    return np.array(temp)

toLeading1(matrix, 0, 0)
    

array([[ 1.        ,  0.66666667,  1.        ,  0.33333333],
       [ 6.        , -4.        ,  1.        ,  2.        ],
       [ 9.        , -2.        ,  4.        ,  3.        ]])

Next part is to perform these functions on  at least a system of 3 functions and three unknown, which I assume to be the same.

In [42]:
A = np.array([[2,1,5,-18], [-3,2,6,-4], [-2,1,2,1]])
B = np.array([[-4, -1, 23], [5, -5, -60]])
swap(A, 0, 1)

array([[ -3,   2,   6,  -4],
       [  2,   1,   5, -18],
       [ -2,   1,   2,   1]])

In [43]:
addRow(A, 0, 1, 3)

array([[ -7,   7,  23, -30],
       [ -3,   2,   6,  -4],
       [ -2,   1,   2,   1]])

In [44]:
toLeading1(A, 1, 0)

array([[  2.        ,   1.        ,   5.        , -18.        ],
       [  1.        ,  -0.66666667,  -2.        ,   1.33333333],
       [ -2.        ,   1.        ,   2.        ,   1.        ]])

In [45]:
swap(B, 0, 1)

array([[  5,  -5, -60],
       [ -4,  -1,  23]])

In [46]:
addRow(B, 0, 1, 3)

array([[  11,  -16, -157],
       [   5,   -5,  -60]])

In [47]:
toLeading1(B, 1, 0)

array([[ -4.,  -1.,  23.],
       [  1.,  -1., -12.]])