# Project 4: Systems of Linear Equation Solving

This week we will go over Gauss-Jordan and the algorithm to solve it.

# Rows function

Firstly, we need to write methods for operation on rows needed for Jordan-Gauss method, which includes adding, swapping, and multiplying.

Please note that I will make a copy of the matrix list and modify parts needed to be changed instead of appending to a totally new list within the function.

In [53]:
import math
import numpy as np

matrix = np.array([[3,2,3,1], [6,-4,1,2], [9,-2,4,3]])


#SWAP ROWS

def swap(matrx, r1, r2):
    temp = matrx.copy()
    temp[[r1, r2]] = temp[[r2, r1]]
    return np.array(temp)

swap(matrix, 1, 2)    


array([[ 3,  2,  3,  1],
       [ 9, -2,  4,  3],
       [ 6, -4,  1,  2]])

In [54]:
#ADD


def addRow(matrx, row, toAdd, multiplier):
    temp = matrx.copy()
    for i in range(len(matrx[row, :])):
        temp[row, i] = temp[row, i] + multiplier*temp[toAdd, i]
    return np.array(temp)

addRows(matrix, 1, 2, 5)


array([[  3,   2,   3,   1],
       [ 51, -14,  21,  17],
       [  9,  -2,   4,   3]])

In [55]:
def toLeading1(matrx, row, col):
    temp = matrx.copy()
    temp = np.array(temp, float)
    temp[row, :] = temp[row, :]/temp[row, col]
    return np.array(temp)

toLeading1(matrix, 0, 0)
    

array([[ 1.        ,  0.66666667,  1.        ,  0.33333333],
       [ 6.        , -4.        ,  1.        ,  2.        ],
       [ 9.        , -2.        ,  4.        ,  3.        ]])

Next part is to perform these functions on  at least a system of 3 functions and three unknown, which I assume to be the same.

In [75]:
A = np.array([[1,5,-3,2], [1,2,-9,-1], [-1,-3,7,0]])


We already have leading zero on row 1, so we can go ahead and skip that step.

In [76]:
A = addRow(A, 1, 0, -1)
A

array([[ 1,  5, -3,  2],
       [ 0, -3, -6, -3],
       [-1, -3,  7,  0]])

In [77]:
A = addRow(A, 2, 0, 1)
A

array([[ 1,  5, -3,  2],
       [ 0, -3, -6, -3],
       [ 0,  2,  4,  2]])

In [78]:
A

array([[ 1,  5, -3,  2],
       [ 0, -3, -6, -3],
       [ 0,  2,  4,  2]])

In [79]:
A = toLeading1(A, 1, 1)
A

array([[ 1.,  5., -3.,  2.],
       [-0.,  1.,  2.,  1.],
       [ 0.,  2.,  4.,  2.]])

In [81]:
A = addRow(A, 0, 1, -5)
A

array([[  1.,   0., -13.,  -3.],
       [ -0.,   1.,   2.,   1.],
       [  0.,   2.,   4.,   2.]])

In [82]:
addRow(A, 2, 1, -2)

array([[  1.,   0., -13.,  -3.],
       [ -0.,   1.,   2.,   1.],
       [  0.,   0.,   0.,   0.]])